# Generated by Django 4.1.5 on 2023-03-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0002_alter_currentweight_cur_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweight',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
