# Generated by Django 4.1.5 on 2023-03-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0004_alter_currentweight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweight',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
