# Generated by Django 4.1.5 on 2023-03-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_alter_currentweight_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweight',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
