# Generated by Django 4.1.5 on 2023-06-02 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quick_Description', models.TextField(max_length=100, null=True)),
                ('Date', models.DateField(auto_now=True)),
                ('Duration_Hours', models.PositiveIntegerField(null=True)),
                ('Exercise_Category', models.CharField(choices=[('CARDIO', 'cardio'), ('STRENGTH TRAINING', 'strength training'), ('FLEXIBILITY', 'flexibility'), ('MUSCULAR ENDURANCE', 'muscular endurance')], max_length=18)),
                ('Mood', models.CharField(choices=[('ENERGIZED', 'energized'), ('EXCITED', 'excited'), ('FATIGUED', 'fatigued'), ('STRESSED', 'stressed'), ('CALM', 'calm'), ('SAD', 'sad')], max_length=9)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='dailyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Journal', models.TextField(default='Record how you are feeling.')),
                ('today', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='calorieTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('target', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
