# Generated by Django 4.1 on 2023-01-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=150)),
                ('Date', models.DateField(auto_now=True)),
                ('Duration', models.TimeField()),
                ('Exercise_Category', models.CharField(choices=[('CARDIO', 'cardio'), ('STRENGTH TRAINING', 'strength training'), ('FLEXIBILITY', 'flexibility'), ('MUSCULAR ENDURANCE', 'muscular endurance')], max_length=18)),
                ('Mood', models.CharField(choices=[('energized', 'ENERGIZED'), ('EXCITED', 'excited'), ('fatigued', 'FATIGUED'), ('STRESSED', 'stressed'), ('CALM', 'calm'), ('SAD', 'sad')], max_length=9)),
            ],
        ),
    ]
