# Generated by Django 4.1 on 2023-01-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_workoutmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmodel',
            name='Description',
            field=models.TextField(max_length=50),
        ),
    ]
