# Generated by Django 4.1 on 2023-01-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_remove_workoutmodel_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutmodel',
            name='Duration_Hours',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
