# Generated by Django 4.1 on 2023-01-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_alter_workoutmodel_duration_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_Journal', models.TextField()),
            ],
        ),
    ]
