# Generated by Django 4.1 on 2023-01-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_dailyjournal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyjournal',
            name='today',
            field=models.DateField(auto_now=True),
        ),
    ]
