# Generated by Django 4.1 on 2023-01-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_dailyjournal_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyjournal',
            name='today',
            field=models.DateField(),
        ),
    ]
