# Generated by Django 4.1 on 2023-01-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0015_rename_user_dailyjournal_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyjournal',
            old_name='person',
            new_name='author',
        ),
    ]
