# Generated by Django 4.1 on 2023-01-12 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0016_rename_person_dailyjournal_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorietracker',
            old_name='user',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='workoutmodel',
            old_name='user',
            new_name='person',
        ),
    ]
