# Generated by Django 4.1.5 on 2023-03-01 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0017_rename_user_calorietracker_person_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutmodel',
            old_name='person',
            new_name='user',
        ),
    ]
