# Generated by Django 4.1.5 on 2023-03-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0018_rename_person_workoutmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorietracker',
            old_name='person',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='dailyjournal',
            old_name='author',
            new_name='user',
        ),
    ]
