# Generated by Django 4.1.5 on 2023-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0019_rename_person_calorietracker_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyjournal',
            name='Upload_Journal',
            field=models.TextField(default='Record how you are feeling.'),
        ),
    ]
