# Generated by Django 4.1.5 on 2023-03-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_friendslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendslist',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='friendslist',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
