# Generated by Django 4.1.5 on 2023-02-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_alter_socialprofile_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank='true', to='social_media.socialprofile')),
            ],
        ),
    ]
