# Generated by Django 4.1.5 on 2023-03-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_friendlist_friendrequest_remove_friends_cur_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
