# Generated by Django 4.1.5 on 2023-03-29 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media', '0011_alter_socialprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
