# Generated by Django 4.1.5 on 2023-03-30 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0013_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
