# Generated by Django 4.1.5 on 2023-03-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0015_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], max_length=8, null=True),
        ),
    ]
