# Generated by Django 4.1.5 on 2023-03-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0016_friend_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted'), ('unfriend', 'unfriend')], max_length=8, null=True),
        ),
    ]
