# Generated by Django 4.1.5 on 2023-04-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0017_alter_friend_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted'), ('unfriended', 'unfriended')], max_length=10, null=True),
        ),
    ]
